// -------- UPLINK -------- // 
#define UPLINK_FREQUENCY 867e6
#define UPLINK_POWER 2
#define UPLINK_BW 125e3
#define UPLINK_SF 8
#define UPLINK_CR 7
#define UPLINK_PREAMBLE_LEN 8
#define UPLINK_SYNC_WORD 0x12
#define UPLINK_CRC true

// -------- AV_DOWNLINK -------- // 
#define AV_DOWNLINK_FREQUENCY 868e6
#define AV_DOWNLINK_POWER 2
#define AV_DOWNLINK_BW 125e3
#define AV_DOWNLINK_SF 8
#define AV_DOWNLINK_CR 7
#define AV_DOWNLINK_PREAMBLE_LEN 8
#define AV_DOWNLINK_SYNC_WORD 0x13
#define AV_DOWNLINK_CRC true

// -------- GSE_DOWNLINK -------- // 
#define GSE_DOWNLINK_FREQUENCY 869e6
#define GSE_DOWNLINK_POWER 2
#define GSE_DOWNLINK_BW 125e3
#define GSE_DOWNLINK_SF 8
#define GSE_DOWNLINK_CR 7
#define GSE_DOWNLINK_PREAMBLE_LEN 8
#define GSE_DOWNLINK_SYNC_WORD 0x14
#define GSE_DOWNLINK_CRC true
